import { z } from "zod";

export const TaskType = z.enum(["planning", "code_generation", "code_modification", "repair", "summarization", "classification"]);
export const Operation = z.object({ type: z.enum(["write_file", "delete_file", "move_file"]), path: z.string().min(1), content: z.string().optional() });
export const GenerationResponse = z.object({ intent: z.string(), summary: z.string(), operations: z.array(Operation).max(100), validationNotes: z.array(z.string()).max(20) });
export type GenerationResponse = z.infer<typeof GenerationResponse>;
export type ProviderHealth = "available" | "unavailable" | "rate_limited" | "misconfigured" | "unknown";
export type GenerationInput = { task: z.infer<typeof TaskType>; request: string; context?: string };
export interface ModelProvider { readonly id: string; readonly models: readonly string[]; health(): Promise<ProviderHealth>; generate(input: GenerationInput & { model?: string }): Promise<{ output: unknown; generationId?: string; latencyMs?: number; usage?: Record<string, unknown> }>; }
export const developmentProvider: ModelProvider = { id: "development", models: ["deterministic-v1"], async health() { return "available"; }, async generate({ request }) { return { output: { intent: "EXPLAIN", summary: request.slice(0, 240), operations: [], validationNotes: ["path validation", "typecheck"] }, usage: {} }; } };
export const modelCatalog = [{ provider: "development", key: "deterministic-v1", capabilities: ["planning", "code_generation", "repair"], contextWindow: 12000, structuredOutput: true, enabled: true }] as const;
export class ModelRouter { readonly providers: readonly ModelProvider[]; constructor(providers: readonly ModelProvider[] = [developmentProvider]) { this.providers = providers; } async route(input: GenerationInput | z.infer<typeof TaskType>) { const normalized: GenerationInput = typeof input === "string" ? { task: input, request: "" } : input; const provider = this.providers[0]; const health = await provider.health(); return { provider, decision: { model: provider.models[0] ?? "unknown", task: normalized.task, fallbackUsed: false }, health }; } }
export async function generateStructured(input: { task: z.infer<typeof TaskType>; prompt: string; context?: string }, router = new ModelRouter()): Promise<GenerationResponse> { const route = await router.route({ task: input.task, request: input.prompt, context: input.context }); if (route.health !== "available") throw new Error("PROVIDER_UNAVAILABLE"); const raw = await route.provider.generate({ task: input.task, request: input.prompt, context: input.context, model: route.decision.model }); return GenerationResponse.parse(raw.output); }
