import { z } from "zod";
import { BillingConflictError, BillingNotFoundError, createInvoice, createPlanPrice, getBillingProfile, getInvoice, issueInvoice, listInvoices, listPlanPrices, recordAudit, recordManualPayment, recordRefund, upsertBillingProfile, voidInvoice } from "@saasweave/db";
import { ORPCError } from "@orpc/server";
import { requirePlatformPermission } from "#@/lib/procedures/factory";

const id = z.string().trim().min(1).max(200);
const currency = z.enum(["BRL", "USD", "EUR"]).default("BRL");
const org = z.object({ organizationId: id });
function safeError(error: unknown): never { if (error instanceof BillingNotFoundError) throw new ORPCError("NOT_FOUND", { message: "BILLING_NOT_FOUND" }); if (error instanceof BillingConflictError) throw new ORPCError("CONFLICT", { message: "BILLING_CONFLICT" }); throw error; }
function dates<T extends Record<string, unknown>>(row: T) { return Object.fromEntries(Object.entries(row).map(([key, value]) => [key, value instanceof Date ? value.toISOString() : value])); }

export const adminBillingRouter = {
  profile: requirePlatformPermission("billing.read").route({ description: "Read workspace billing profile", method: "GET" }).input(org).handler(({ input }) => getBillingProfile(input.organizationId)),
  prices: requirePlatformPermission("billing.read").route({ description: "List immutable plan prices", method: "GET" }).input(z.object({ planId: id })).handler(async ({ input }) => (await listPlanPrices(input.planId)).map(dates)),
  invoices: requirePlatformPermission("billing.read").route({ description: "List workspace invoices", method: "GET" }).input(org.extend({ limit: z.number().int().min(1).max(100).default(50) })).handler(async ({ input }) => (await listInvoices(input.organizationId, input.limit)).map(dates)),
  invoice: requirePlatformPermission("billing.read").route({ description: "Get an invoice with line item snapshots", method: "GET" }).input(org.extend({ id })).handler(async ({ input }) => { const row = await getInvoice(input.organizationId, input.id); if (!row) throw new ORPCError("NOT_FOUND", { message: "BILLING_NOT_FOUND" }); return { ...dates(row), lines: row.lines.map(dates) }; }),
  createPrice: requirePlatformPermission("billing.write").route({ description: "Create an immutable plan price", method: "POST" }).input(z.object({ planId: id, currency, interval: z.enum(["month", "year", "one_time"]), amountMinor: z.number().int().nonnegative().max(2_147_483_647) })).handler(async ({ context, input }) => { const row = await createPlanPrice(input); await recordAudit({ actorId: context.session.user.id, actorName: context.session.user.name, action: "billing.price_created", targetType: "plan_price", targetLabel: row.id, metadata: { planId: input.planId, currency: input.currency, interval: input.interval } }); return dates(row); }),
  saveProfile: requirePlatformPermission("billing.write").route({ description: "Update workspace billing profile", method: "POST" }).input(org.extend({ legalName: z.string().trim().max(300).nullable().optional(), taxId: z.string().trim().max(50).nullable().optional(), billingEmail: z.email().nullable().optional(), address: z.unknown().optional() })).handler(async ({ context, input }) => { const row = await upsertBillingProfile(input); await recordAudit({ actorId: context.session.user.id, actorName: context.session.user.name, action: "billing.profile_updated", organizationId: input.organizationId, targetType: "billing_profile", targetLabel: input.organizationId }); return row; }),
  createInvoice: requirePlatformPermission("billing.write").route({ description: "Create a server-totaled invoice", method: "POST" }).input(z.object({ organizationId: id, subscriptionId: id.optional(), currency, dueAt: z.coerce.date().nullable().optional(), lines: z.array(z.object({ description: z.string().trim().min(1).max(500), quantity: z.number().int().positive().max(1_000_000), unitAmountMinor: z.number().int().nonnegative().max(2_147_483_647), snapshot: z.unknown().optional() })).min(1).max(100) })).handler(async ({ context, input }) => { try { const row = await createInvoice(input); await recordAudit({ actorId: context.session.user.id, actorName: context.session.user.name, action: "billing.invoice_created", organizationId: input.organizationId, targetType: "invoice", targetLabel: row.id, metadata: { totalMinor: row.totalMinor } }); return dates(row); } catch (error) { return safeError(error); } }),
  issue: requirePlatformPermission("billing.write").route({ description: "Issue an invoice", method: "POST" }).input(org.extend({ id })).handler(async ({ context, input }) => { try { const row = await issueInvoice(input.organizationId, input.id); await recordAudit({ actorId: context.session.user.id, actorName: context.session.user.name, action: "billing.invoice_issued", organizationId: input.organizationId, targetType: "invoice", targetLabel: input.id }); return dates(row); } catch (error) { return safeError(error); } }),
  void: requirePlatformPermission("billing.write").route({ description: "Void an invoice", method: "POST" }).input(org.extend({ id })).handler(async ({ context, input }) => { try { const row = await voidInvoice(input.organizationId, input.id); await recordAudit({ actorId: context.session.user.id, actorName: context.session.user.name, action: "billing.invoice_voided", organizationId: input.organizationId, targetType: "invoice", targetLabel: input.id }); return dates(row); } catch (error) { return safeError(error); } }),
  payment: requirePlatformPermission("billing.write").route({ description: "Record a manual payment", method: "POST" }).input(z.object({ organizationId: id, invoiceId: id, amountMinor: z.number().int().positive().max(2_147_483_647), currency, method: z.string().trim().min(1).max(50).default("manual"), provider: z.string().trim().max(100).optional(), reference: z.string().trim().max(300).optional(), idempotencyKey: z.string().trim().min(1).max(255) })).handler(async ({ context, input }) => { try { const result = await recordManualPayment(input); if (!result.duplicate) await recordAudit({ actorId: context.session.user.id, actorName: context.session.user.name, action: "billing.payment_recorded", organizationId: input.organizationId, targetType: "manual_payment", targetLabel: result.payment.id, metadata: { amountMinor: input.amountMinor } }); return { ...result, payment: dates(result.payment) }; } catch (error) { return safeError(error); } }),
  refund: requirePlatformPermission("billing.write").route({ description: "Record a manual refund", method: "POST" }).input(z.object({ organizationId: id, paymentId: id, amountMinor: z.number().int().positive().max(2_147_483_647), method: z.string().trim().min(1).max(50).default("manual"), provider: z.string().trim().max(100).optional(), reason: z.string().trim().max(500).optional(), idempotencyKey: z.string().trim().min(1).max(255) })).handler(async ({ context, input }) => { try { const result = await recordRefund(input); if (!result.duplicate) await recordAudit({ actorId: context.session.user.id, actorName: context.session.user.name, action: "billing.refund_recorded", organizationId: input.organizationId, targetType: "refund", targetLabel: result.refund.id, metadata: { amountMinor: input.amountMinor } }); return { ...result, refund: dates(result.refund) }; } catch (error) { return safeError(error); } })
};
