CREATE SEQUENCE invoice_number_seq;
CREATE TABLE "plan_price" ("id" text PRIMARY KEY, "plan_id" text NOT NULL REFERENCES "plan"("id"), "currency" text NOT NULL DEFAULT 'BRL', "interval" text NOT NULL CHECK ("interval" IN ('month','year','one_time')), "amount_minor" integer NOT NULL CHECK ("amount_minor" >= 0), "effective_from" timestamp DEFAULT now() NOT NULL, "effective_to" timestamp, "created_at" timestamp DEFAULT now() NOT NULL);
CREATE INDEX "plan_price_plan_effective_idx" ON "plan_price" ("plan_id", "effective_from");
CREATE TABLE "workspace_billing_profile" ("organization_id" text PRIMARY KEY REFERENCES "organization"("id") ON DELETE CASCADE, "legal_name" text, "tax_id" text, "billing_email" text, "address" jsonb, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
CREATE TABLE "invoice" ("id" text PRIMARY KEY, "organization_id" text NOT NULL REFERENCES "organization"("id") ON DELETE CASCADE, "number" text NOT NULL UNIQUE, "status" text NOT NULL DEFAULT 'draft' CHECK ("status" IN ('draft','issued','paid','void')), "currency" text NOT NULL DEFAULT 'BRL', "subtotal_minor" integer NOT NULL DEFAULT 0 CHECK ("subtotal_minor" >= 0), "total_minor" integer NOT NULL DEFAULT 0 CHECK ("total_minor" >= 0), "issued_at" timestamp, "due_at" timestamp, "paid_at" timestamp, "voided_at" timestamp, "created_at" timestamp DEFAULT now() NOT NULL, "updated_at" timestamp DEFAULT now() NOT NULL);
CREATE INDEX "invoice_org_created_idx" ON "invoice" ("organization_id", "created_at"); CREATE INDEX "invoice_status_idx" ON "invoice" ("status", "created_at");
CREATE TABLE "invoice_line_item" ("id" text PRIMARY KEY, "invoice_id" text NOT NULL REFERENCES "invoice"("id") ON DELETE CASCADE, "description" text NOT NULL, "quantity" integer NOT NULL CHECK ("quantity" > 0), "unit_amount_minor" integer NOT NULL CHECK ("unit_amount_minor" >= 0), "total_minor" integer NOT NULL CHECK ("total_minor" >= 0), "snapshot" jsonb, "created_at" timestamp DEFAULT now() NOT NULL); CREATE INDEX "invoice_line_invoice_idx" ON "invoice_line_item" ("invoice_id");
CREATE TABLE "manual_payment" ("id" text PRIMARY KEY, "invoice_id" text NOT NULL REFERENCES "invoice"("id"), "organization_id" text NOT NULL REFERENCES "organization"("id") ON DELETE CASCADE, "amount_minor" integer NOT NULL CHECK ("amount_minor" > 0), "currency" text NOT NULL DEFAULT 'BRL', "reference" text, "idempotency_key" text NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, UNIQUE ("organization_id", "idempotency_key")); CREATE INDEX "manual_payment_invoice_idx" ON "manual_payment" ("invoice_id");
CREATE TABLE "refund" ("id" text PRIMARY KEY, "payment_id" text NOT NULL REFERENCES "manual_payment"("id"), "organization_id" text NOT NULL REFERENCES "organization"("id") ON DELETE CASCADE, "amount_minor" integer NOT NULL CHECK ("amount_minor" > 0), "reason" text, "idempotency_key" text NOT NULL, "created_at" timestamp DEFAULT now() NOT NULL, UNIQUE ("organization_id", "idempotency_key")); CREATE INDEX "refund_payment_idx" ON "refund" ("payment_id");
